### ISSUE TITLE
get_RAI()

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#15]
function that calulates the RAI for each deployment (same logic as other get_functions)

- [x] For each camera we calculated RAIs as the number of pictures per 100 trap days (O’Brien et al., 2003)

two questions:

- [x] will we subsequently use the result of the get_functions as input for map_dp() => would be locical way to first get(calculate) deployment characteristics and subsequenlty use these in map_dp() to visualise the result on map (other visualisations still to be developped (bar graphs ?)
- [x] do you prefer me to make more suggestions or to start writing the get_functions also ?

**Comment by damianooldoni** [comment]
##First question

About first question: I treated the get_* functions up to now as "internal" functions to be used in `map_dep()` so that user can easily get visualizations just providing a data package and the kind of information he/she wants, e.g. `n_species`. I like this approach as it is easy. 

But I made the get_* functions  "public" (= callable by user) so that people are allowed to get these features as a df. In this way they can for example run statistics, model stuff, making any other kind of visualization...

So, I personally would continue on this way.

## Second question

Up to now I can write code fast enough to handle your issues in a decent tempo, so I would continue like that. If I see I cannot develop things fast you can jump in :+1:

**Comment by damianooldoni** [comment]
See https://inbo.github.io/camtrapdp/articles/visualize-deployment-features.html#basic-usage to see how to visualize RAIs via `map_dep()`.

**Comment by damianooldoni** [comment]
In R (and for sure in tidyverse style) the functions are always lowercase, so I wrote `get_rai()` function instead of `get_RAI()`.
