### ISSUE TITLE
get_effort

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#16]
- [ ] calculates effort per dp

1. [ ] expressed as number of hours between depl_start & depl_end
2. [ ] expressed as number of days between depl_start & depl_end

**Comment by damianooldoni** [comment]
I would return `effort` as value(s) of type `duration` from lubridate paclage, instead of converting them to numeric values (hours or days). 

From lubridate package documentation: 
> Durations are stored as seconds, the only time unit with a consistent length.
Difftimes are a class of durations found in base R.

basic difftime R visualizes it as days:

```r
> camtrapdp$deployments$end - camtrapdp$deployments$start
Time differences in days
[1] 30.026713 21.099942  3.182153  4.126262
```

Still, I would really benefit of the lubridate duration as indeed seconds are the best time unit to handle durations (the second is THE time unit in the International System of Units, SI)

```r
> as.duration(camtrapdp$deployments$end - camtrapdp$deployments$start)
[1] "2594308s (~4.29 weeks)" "1823035s (~3.01 weeks)" "274938s (~3.18 days)"   "356509s (~4.13 days)"  
```

When calculating RAI or any other index based on effort, we can then convert these durations to number of days or hours (numeric values).

**Comment by jimcasaer** [comment]
the effort on its own is often also a important characteristic of a research project so it should be easily to summarise over different characteristics later on (habitattype, year, deployment feature, season , .....) 

I guess seconds is ok -- afterwards users can convert it to days / hours

**Comment by damianooldoni** [comment]
Great. In this way the researchers can use the unit they want as we return a duration object. Soon in the next PR...

**Comment by damianooldoni** [comment]
Just to trace back things, converting period objects to common time units such as days/months/... is important for visualization. So, it has been tackled in #22. You can check the vignette [visualize-deployment-features.html#effort](https://inbo.github.io/camtrapdp/articles/visualize-deployment-features.html#effort).
Not only, the conversion to common units has been put in a function, `transform_effort_to_common_units()` so that it can be used by everybody and not only for map_dep() but also for tables, ...

See help of `?transform_effort_to_common_units`

An example using camtrapdp data package:

```r
library(camtrapdp)
library(dplyr)
get_effort(camtrapdp) %>%
  mutate(effort = transform_effort_to_common_units(effort, unit = "day"))
```
