### ISSUE TITLE
camera operation table contains decimal figures

### ISSUE THREAD

**Issue by jimcasaer** [inbo/camtrapdp#75]
the result op get_cam_op contains for some days decimal figures => not sure this does not pose problems for further use

**Comment by jimcasaer** [comment]
to discuss because two different problems

**Comment by damianooldoni** [comment]
Just decided with @jimcasaer to do the following:

1. the camera operation matrix as returned now should be an internal intermediate step
2. `get_cam_op()` will read the intermediate result and will round up the decimal figures
3. the intermediate matrix will be used by `get_custom_effort()` to return exact (decimal) effort

**Comment by damianooldoni** [comment]
Solved by adding argument `use_decimal` to `get_cam_op()`. In this way everything works smoothly and implementation was straightforward and more logical. I pushed to main branch instead of making a new branch with PR, my fault. Luckily everything was well tested before pushing and so package works fine.

**Comment by damianooldoni** [comment]
See https://inbo.github.io/camtrapdp/articles/camera-operation-matrix.html for more information about `get_cam_op()`.
